version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
      - db
    links:
      - db
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
  db:
    container_name: db 
    image: mysql:5.7
    networks:
      - webnet
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}      
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
networks:
  webnet:
volumes:
  my-db: